### PR TITLE
add match to envvar

### PR DESCRIPTION
**Pull request by siperman**

### CODE REVIEW

**Review by viswajithiii — COMMENTED** [review]
I'm a bit confused. Can you explain the use-case for this `Match` parameter?

**Comment by siperman** [comment]
use-case:
Different teams need to check whether the format of environment variables is uniform.
It is also necessary to check that the environment variable conforms to a regular expression.

eg:
AppDynamics app name:  ^WEALTH\-(\w{2})\-(\w{4})\-[\w_]+\-(DEV|UAT|PROD)$

**Comment by viswajithiii** [comment]
I understand that. But can't this be achieved under the status quo? How does this new parameter help?

**Comment by siperman** [comment]
Because my test reverses the entire regular, it does not take effect. Remember that the reason for the search is that the golang regular library does not support inversion.

**Comment by viswajithiii** [comment]
> Because my test reverses the entire regular, it does not take effect. Remember that the reason for the search is that the golang regular library does not support inversion.

Ohh I see. Yeah, we currently support this by allowing people to add a `!` at the beginning, to signify negation. This is probably not as well-documented as it should be.

**Comment by viswajithiii** [comment]
@siperman You should be able to set the value in the check to `!^WEALTH-(\w{2})-(\w{4})-[\w_]+-(DEV|UAT|PROD)$`, and then I think it will do what you want?

**Comment by janisz** [comment]
@siperman What's the status of this?

**Comment by janisz** [comment]
Closing due to no activity on this.
If you like to work on this please reopen or create a new PR.

**Pull request closed without merging**
