### PR TITLE
Check if Service has Endpoints for dangling service template

### LINKED ISSUE #746: [BUG] - service has no selector specified raised when using Endpoint
**System info:**
 - OS: [e.g. Linux? MaxOS? Windows?]

**Describe the bug**
If I use both Service and Endpoint manifests, Kube Linter raises :
```
/manifests/service-mt1.yaml: (object: service-mt1 /v1, Kind=Service) service has no selector specified (check: dangling-service, remediation: Confirm that your service's selector correctly matches the labels on one of your deployments.)
```

**To Reproduce**
Run Kube Linter with the below sample.

**Sample YAML input**
If applicable, sample YAML input which reproduces the issue.
```
---
kind: Endpoints
apiVersion: v1
metadata:
  name: service-mt1
subsets:
  - addresses:
      - ip: 10.1.2.3
    ports:
      - name: https
        port: 443

---
apiVersion: v1
kind: Service
metadata:
  name: service-mt1
spec:
  ports:
    - name: https
      port: 443
      targetPort: 443

```

**Expected behavior**

Kube Linter should be aware that this Service is linked to the Endpoint and selector is not necessary, so no need to raise the error.

**Screenshots**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by marcmognol**
# Motivation

Fix #746 

# Changed
This PR update dangling-service template.
When no selector is specified on the Service, check if Endpoints exists in the context with the same name and namespace.

### CODE REVIEW

**Review by janisz — CHANGES_REQUESTED** [review]
Could you add sample from 
- https://github.com/stackrox/kube-linter/issues/746
to 
https://github.com/stackrox/kube-linter/blob/49aa5bb98089ccc797ea5ab0e955012f42167e8a/e2etests/bats-tests.sh#L131-L134

**Comment by marcmognol** [comment]
Hi @janisz,
Is it better now ?
Marc

**Comment by rassie** [comment]
Is there a reason this has been closed? Would also be cool, if this could be extended for `EndpointSlice`s too.

**Comment by janisz** [comment]
It's probably my fault. If I'm not rerequested (:recycle:) for a review I do not look at it :(
@marcmognol would you like to reopen and rebase your PR

**Pull request closed without merging**
