### PR TITLE
feat: add PodDisruptionBudget kind to registered objectkinds

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Review by janisz — COMMENTED** [review]
Could you add test for this change?

**Comment by tremes** [comment]
@janisz yes I can. I am just wondering how these object kinds are tested......

**Comment by janisz** [comment]
Probably the best way to add object kind is with a template that uses it. Then you can add it in mocks and use in unit tests and/or add a e2e tests.

Here is a tutorial how to add a new check https://www.psaggu.com/upstream-contribution/2021/08/17/notes.html

**Comment by janisz** [comment]
Closing in favour of https://github.com/stackrox/kube-linter/pull/507

**Pull request closed without merging**
